#set env vars
set -o allexport; source .env; set +o allexport;

LOWCODER_DB_ENCRYPTION_PASSWORD=$(openssl rand -base64 32)
LOWCODER_DB_ENCRYPTION_SALT=$(openssl rand -base64 32)
LOWCODER_API_KEY_SECRET=$(openssl rand -base64 32)

cat << EOT >> ./.env

LOWCODER_DB_ENCRYPTION_PASSWORD=${LOWCODER_DB_ENCRYPTION_PASSWORD}
LOWCODER_DB_ENCRYPTION_SALT=${LOWCODER_DB_ENCRYPTION_SALT}
LOWCODER_API_KEY_SECRET=${LOWCODER_API_KEY_SECRET}
MONGO_INITDB_ROOT_PASSWORD=${ADMIN_PASSWORD}
EOT